### PR TITLE
create react app with added router and apollo

### LINKED ISSUE #2: Start React App
Minimal requirement is that App is working

### PR DESCRIPTION
**Pull request by Graleszczur**
close #2  #6 
Setup react app using create-react-app
setup react router
setup react-apollo 
create basic funcionality 
Adnotacja 2019-09-27 184808

### CODE REVIEW

**Comment by konieczka** [comment]
LGTM ;)

**Comment by bopke** [comment]
veri gud PR its really great work as always mi friend

**Comment by hakun12** [comment]
Approved by frontend team leader, good to merge, 420/10, this is Google tier code

**Review by bopke — COMMENTED** [review]
everything ok

**Review by konieczka — APPROVED** [review]
Approved by frontend team leader, good to merge, 420/10, this is Google tier code

**Pull request merged**
